# Learn more about configuring your app at https://shopify.dev/docs/apps/tools/cli/configuration

client_id = "2a306ab89a3d6fa5318182e8c8d4c667"
name = "DC External Links"
handle = "dc-external-links"
application_url = "https://fs-hz-balanced-story.trycloudflare.com"
embedded = true

[build]
include_config_on_deploy = true
automatically_update_urls_on_dev = true

[webhooks]
api_version = "2025-04"

  [[webhooks.subscriptions]]
  topics = [ "app/uninstalled" ]
  uri = "/webhooks/app/uninstalled"

  [[webhooks.subscriptions]]
  topics = [ "app/scopes_update" ]
  uri = "/webhooks/app/scopes_update"

[access_scopes]
# Learn more at https://shopify.dev/docs/apps/tools/cli/configuration#access_scopes
scopes = "read_products,write_products"

[[metafields.definitions]]
namespace = "bl_custom_button"
key = "external_url"
name = "External Button URL"
description = "URL for the custom external link button."
type = "url"
owner_type = "PRODUCT"

[[metafields.definitions]]
namespace = "bl_custom_button"
key = "button_text"
name = "External Button Text"
description = "Text to display on the custom external link button."
type = "single_line_text_field"
owner_type = "PRODUCT"

[[metafields.definitions]]
namespace = "bl_custom_button"
key = "is_enabled"
name = "Enable External Button"
description = "Enable this custom button for the product."
type = "boolean"
owner_type = "PRODUCT"

[[metafields.definitions]]
namespace = "bl_custom_button"
key = "hide_atc"
name = "Hide Add to Cart Button"
description = "Hide the original Add to Cart button if external button is enabled."
type = "boolean"
owner_type = "PRODUCT"

[auth]
redirect_urls = [
  "https://fs-hz-balanced-story.trycloudflare.com/auth/callback",
  "https://fs-hz-balanced-story.trycloudflare.com/auth/shopify/callback",
  "https://fs-hz-balanced-story.trycloudflare.com/api/auth/callback"
]

[pos]
embedded = false
