name = "remix"
roles = ["frontend", "backend"]
webhooks_path = "/webhooks/app/uninstalled"

[commands]
# predev = "npx prisma generate"  # Temporarily commented due to Windows permission issue
dev = "npm exec remix vite:dev"  # Removed prisma migrate deploy temporarily
