name = "dc-external-links"
main = "worker.js"
compatibility_date = "2024-11-27"
compatibility_flags = ["nodejs_compat"]

[build]
command = "npm run build"

[assets]
directory = "./build/client"

[vars]
NODE_ENV = "production"
SHOPIFY_API_KEY = "2a306ab89a3d6fa5318182e8c8d4c667" 