name = "dc-external-links"
compatibility_date = "2024-11-27"
compatibility_flags = ["nodejs_compat"]

[build]
command = "npm run build"

[[build.upload]]
format = "modules"
dir = "./build/client"

[build.upload.rules]
"**/*.js" = "module"
"**/*.mjs" = "module"

[[env.production]]
name = "dc-external-links-production"

[env.production.vars]
NODE_ENV = "production"
SHOPIFY_API_KEY = "2a306ab89a3d6fa5318182e8c8d4c667"

[env.production.compatibility_flags]
nodejs_compat = true 